### ISSUE TITLE
Privacy concerns re: automated data collection

### ISSUE THREAD

**Issue by TRSx80** [armbian/autotests#1]
I know this is still very WIP, but I wanted to lodge a concern, while I was thinking about it.

I hope that any automated data collection will be opt-in, when the time comes around to implement that functionality.

I realize how important this functionality will be to the overall stability of Armbian, but I would like to see us do "the Right Thing" here (when the time comes).

Perhaps a good compromise would be to ask the user upon installation? Perhaps with some message about how this contributes to stability, a link to this repository, or whatever...

**Comment by igorpecovnik** [comment]
> I hope that any automated data collection will be opt-in

Absolutely. In a first stage this tool will be used in our lab(s) to determine boards functions. Only later if we manage to, we will collect data from more sources. From anyone that will be participating in this.

You will need to run this thing manually and accept terms. I don't see any concerns.
